spring:
  flyway:
    table: schema_history
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/streamarr
    username: admin
    password: pass

  profiles:
    active: dev

  threads:
    virtual:
      enabled: true

dgs:
  graphql:
    graphiql:
      enabled: false
    introspection:
      enabled: false

tmdb:
  api:
    token: ${TMDB_API_TOKEN:}
